name: Maven Build

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
    types:
      - opened
      - synchronize
      - reopened
      - ready_for_review

jobs:
  build:
    name: "Maven Build"
    runs-on: ubuntu-latest

    steps:
      - name: "Checkout Sources"
        uses: actions/checkout@v2
        with:
          # We must fetch at least the immediate parents so that if this is
          # a pull request then we can checkout the head.
          fetch-depth: 2
      - name: "Set up JDK"
        uses: actions/setup-java@v2
        with:
          distribution: "temurin"
          java-version: 17-ea
          cache: "maven"
      - name: "Build with Maven"
        run: ./mvnw verify
